// const baseUrl = 'http://192.169.243.70:3000/v1/';//(LOCAL)
const baseUrl = 'https://www.mahalli.com/v1/';//(HTTPS)

export const AppSettings = {
    registrationUrl: baseUrl + 'vendors/registration',
    loginUrl: baseUrl + 'vendors/login',
    changePwdUrl: baseUrl + 'vendors/change_password',
    categoriesUrl: baseUrl + 'categories/ecommers',
    productUrl: baseUrl + 'products',
    loginDetailsbyEmail: baseUrl + 'vendors/',
    getWholeSellersUrl: baseUrl + 'wholesalers',
    updateProfile: baseUrl + 'vendors/update_profile',
    forgotPw: baseUrl + 'vendors/forgot_password',
    addaddress: baseUrl + "delivery_address",
    getAddress: baseUrl + "delivery_address",
    delAddress: baseUrl + "delivery_address",
    updateAddress: baseUrl + "delivery_address",
    businessDetails: baseUrl + "vendors/update_profile",
    taxDetails: baseUrl + "vendors/update_profile",
    bankDetails: baseUrl + "vendors/update_profile",
    getBanners: baseUrl + "banners/e_commerce",
    productByCatId: baseUrl + "products/category",
    productBySubCatId: baseUrl + "products/sub_category_id",
    searchProducts: baseUrl + 'products/search',
    addToCart: baseUrl + "vendor/cart_details",
    getCart: baseUrl + 'vendor/cart_details/ecommerce',
    delCart: baseUrl + 'vendor/cart_details',
    paymentType: baseUrl + "payment_options",
    palceOrder: baseUrl + "place_order",
    orderSummary: baseUrl + "place_order/order_summary",
    getAccDetails: baseUrl + "vendors/account_details",
    getAddbyId: baseUrl + "delivery_address/address_id",
    updateAcc: baseUrl + "vendors/update_profile",
    dealOfDay: baseUrl + "products/e_commerce/dashboard",
    getJewel: baseUrl + "products/jewellery",
    getCloth: baseUrl + "products/cloths",
    ProductById: baseUrl + "products/product_id",
    // ecomProducts: baseUrl + "products/e_commerce",
    ecomProducts: baseUrl + "products/getecommersproducts",
    getPlaceOrd: baseUrl + "place_order/vendor_orders/ecommerce/vendor_id",
    ordById: baseUrl + "place_order/order_products",
    reqProducts: baseUrl + "place_order/request_products/vendor",
    updateProd: baseUrl + "vendor/products",
    filterVendor: baseUrl + "products/filter/vendor",
    getAddedData: baseUrl + "vendor_products/ecommers",
    delProd: baseUrl + "vendor_products/product",
    getFooter: baseUrl + "footer_table/getfooter/",
    getEcomVenProds: baseUrl + "products/getecommersproducts",
    getUserOrders: baseUrl + "place_order/getuserorders/ecommers",
    requestAdmin: baseUrl + "products/requestnewproduct",
    shoEcomCats: baseUrl + "categories/getcategories/showinvenderecommers",
    updateUserOrd: baseUrl + "vendor/cart_details/updatecart", //new
    otpUrl: baseUrl + "vendors/request_otp",
    changeForgot: baseUrl + "vendors/changepassword",
    updategetCart: baseUrl + "vendor/cart_details/updateuserorvenderid/session",
    modifyCart: baseUrl + "vendor/cart_details",
    getBrands: baseUrl + "products/getbrandsbycat/ecom",
    filterByBrandCat: baseUrl + "products/filtercatproducts/brand",
    filterByBrandSubCat: baseUrl + "products/filtersubcatproducts/brand",
    filterByBrandDeals: baseUrl + "products/filterdealsofthedayecommersproducts/brand",
    filterByBrandTopOff: baseUrl + "products/filtertopoffersecommersproducts/brand",
    filterByBrandRec: baseUrl + "products/filterecommersproducts/brand",
    getEcomDeals: baseUrl + "products/getdealsofthedayecommersproducts",
    getEcomTopOffers: baseUrl + "products/gettopoffersecommersproducts",
    getUserOrdByVenId: baseUrl + "place_order/getvendorecomuserorders",
    orderDetByVenId: baseUrl + "place_order/order_userproducts",
    checkQuty: baseUrl + "vendor/cart_details/stockavailable",
    getBannerProds: baseUrl + "banners/bannerproducts",
    getDetailsById: baseUrl + "vendors/vendor_id",
    forgotwithEmail: baseUrl + "vendors/forgot_passwordbyemail",

}

